[package]
name = "vesting_wallet"
version = "0.1.0"

[dependencies]
starknet = ">=2.0.1"

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
sierra = true

[crate_roots]
test_crate = "src"